version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "arti-serverless-api-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9rr7iwbk7jdb"
s3_prefix = "arti-serverless-api-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "arti"
disable_rollback = true
